### ISSUE TITLE
Stereo PIV

### ISSUE THREAD

**Issue by omidne** [alexlib/openpiv-matlab#2]
Hello Dear Alex
Thanks for sharing great software. I have on question, Is there any StereoPIV part in OPEN PIV?

Sincerely yours
Omid

**Comment by alexlib** [comment]
Hello, 
Unfortunately not, it's on our long list of things to do, but never managed really. our another project OpenPTV provides us the 3D results we need, so we hardly work with StereoPIV at all. 
Please also note that most of the development is in the openpiv-python branch. Join the Google forum `openpiv-users` to get more info. Maybe you'll find there people that need/want to develop StereoPIV part.
