### ISSUE TITLE
Cannot load images - openpiv_imread function

### ISSUE THREAD

**Issue by garettf** [alexlib/openpiv-matlab#6]
The openpiv_imread function is called in line 406 with two arguments but the function only accepts one.

![Capture](https://user-images.githubusercontent.com/31256479/77594021-c2923680-6ecb-11ea-93c8-b49a9d1fce16.PNG)

**Comment by garettf** [comment]
This is for the 2018a version

**Comment by alexlib** [comment]
@garettf with the demo images?
