### ISSUE TITLE
Error Loading Images

### ISSUE THREAD

**Issue by s-buchan** [alexlib/openpiv-matlab#7]
Hello!

I think I am having the same error as the user garretff, but I can't see how that was resolved.  When I click 'load' I get this series of errors:

_Reference to non-existent field 'edit_path'.

Error in readImDir>update_gui (line 256)
set(handles.edit_path,'String',handles.path);

Error in readImDir>readImDir_OpeningFcn (line 53)
update_gui(hObject,[],handles);

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in readImDir (line 18)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in openpivgui>load_Callback (line 380)
[handles.files,handles.path] = readImDir;

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in openpivgui (line 42)
    gui_mainfcn(gui_State, varargin{:});_

I can't select which files to load, I just get an error straight away.
I am using MATLAB 2018b. 
Any help would be much appreciated.

Thanks!

**Comment by alexlib** [comment]
this is all related to the Matlab version - which Matlab do you use? if you use < 2018a - please download the pre-2018 version of the package, if you use 2018a+ version, then the latest should work.

**Comment by alexlib** [comment]
@sandybuck we can try to look together on your machine using Teamviewer. send me your details in private to alexlib at tauex dot tau dot ac dot il (of course replace the at by @ and dot by .)

**Comment by alexlib** [comment]
@sandybuck please check the present version - i think I fixed it and pulled the updated one from openpiv

**Comment by s-buchan** [comment]
Yes that's fixed it! Thank you very much for your quick response and fix!
